---
name: "CODEX processing tonsil"
NuclearExpansionSegmentationCellpose:
    cache: "."
    nucleus_segmentation:
        model: "nuclei"
    kernel_size: 3
HDF5CellExtraction:
    compression: True
    threads: 20  # threads used in multithreading
    image_size: 36 # image size in pixel
    normalize_output: False
CellFeaturizer:
    batch_size: 800
    dataloader_worker_number: 10
    inference_device: "auto"
    cache: "."
    label: "CellFeaturizer_all"